### ISSUE TITLE
Unable to write output file.

### ISSUE THREAD

**Issue by veltig-jaychoi** [Romanysoft/DataStorm#1]
When attempting to convert a JSON file to XML, I get the an "Unable to write output file" error, but no further details are available.

**Comment by jetiny8** [comment]
I'm sorry for inconviencing you, Please make sure the directory exists and is writeable, I will add the error log later.

**Comment by veltig-jaychoi** [comment]
The output folder is the same folder as where the files to be converted are imported from.  I have read/write permissions to that folder.
