### ISSUE TITLE
Unable to write Output File

### ISSUE THREAD

**Issue by patrick-jussi** [Romanysoft/DataStorm#4]
Converting simple XML to CSV. There appears to be no way to attach the file here or past it.

Regards

**Comment by lauer3912** [comment]
@patrick-jussi  Which version?

**Comment by patrick-jussi** [comment]
Version 4.16 (201507310854)

**Comment by lauer3912** [comment]
@patrick-jussi 
Mac OS X version number?

**Comment by patrick-jussi** [comment]
10.10.5 (14F27)

Patrick

**Comment by lauer3912** [comment]
@patrick-jussi  try  https://github.com/Romanysoft/DataStorm/blob/master/test/DataStorm_20150912.zip
