### ISSUE TITLE
Conversion not working

### ISSUE THREAD

**Issue by pkonior** [Romanysoft/DataStorm#5]
I have a 10 MB file. This is the message I'm receiving
<img width="1016" alt="screen shot 2015-10-05 at 3 35 39 pm" src="https://cloud.githubusercontent.com/assets/14984876/10291409/a04e86d4-6b77-11e5-9d3d-27743ab1503a.png">

**Comment by pkonior** [comment]
This is the message when I receive when I tried to attach the file.
Yowza, that’s a big file.  Try again with a file smaller than 10MB.

**Comment by pkonior** [comment]
does the app have a limit to file size?

**Comment by lauer3912** [comment]
In two days, we will send a test version to you, you try again

**Comment by lauer3912** [comment]
@pkonior In two days, we will send a test version to you, you try again

**Comment by pkonior** [comment]
Thanks

Peter

**Comment by lauer3912** [comment]
@pkonior  https://github.com/Romanysoft/DataStorm/blob/master/test/DataStorm_20150912.zip

**Comment by pkonior** [comment]
I'm still getting the same error "unable to write to output file"

**Comment by pkonior** [comment]
Ian,
The app still does not work!

On Fri, Oct 9, 2015 at 8:40 AM, Ian notifications@github.com wrote:

> @pkonior https://github.com/pkonior
> https://github.com/Romanysoft/DataStorm/blob/master/test/DataStorm_20150912.zip
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/Romanysoft/DataStorm/issues/5#issuecomment-146856510.

## 

Peter J. Konior
peter.konior@gmail.com
845 664 0557
